### ISSUE TITLE
Create an automatic email send of new podcasts to subscribers of the loyalty minute

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/pgg-site#4]
Can you please look into the theme on theloyaltyminute and see if there is a functionality that would allow the system to automatically add these podcast subscribers to a mailing list within the theme, and then send them an email when there is a new podcast uploaded that includes the tag (or is in the category "insightful conversations").

Thanks,

Rob
Hide quoted text

---------- Forwarded message ---------
From: The Loyalty Minute Podcast <subscribe@theloyaltyminute.com>
Date: Sat, Apr 9, 2022, 11:04 PM
Subject: The Loyalty Minute Podcast Subscription "[your-subject]"
To: <robgallo@theloyaltyminute.com>

From: Todd <tipping.todd36@outlook.com>
Subject: [your-subject]

--
This e-mail was sent from the Subscription form on The Loyalty Minute Podcast (https://theloyaltyminute.com)

**Comment by MaksymZerkakh** [comment]
I'll need more information, where are the podcast subscribers located? Do you have a mailing service?

**Comment by robgpeak** [comment]
I never set one up.  Maybe we can get on a call later or tomorrow.  It is a low priority

**Comment by MaksymZerkakh** [comment]
Sounds good, we can do one tomorrow. Let me know what time works for you.
