### ISSUE TITLE
The WP Admin button in rewaresevertsg returns HTML?

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/pgg-site#5]
Please have a look at this and see if you can fix it.

https://youtube.com/shorts/SUMn_PKrVNw?feature=share

**Comment by MaksymZerkakh** [comment]
Hmm, I'm not getting this problem. Clear browser cache and try again. I can't seem to replicate the issue.

**Comment by robgpeak** [comment]
Strange.  It's working fine on my computer, but not on my phone.  I can get into other sites from my phone like theloyaltyminstg with no problem.  I cleared my cache and even tried from incognito and I got the same thing.

Can you try from your phone to see if you can replicate it?

**Comment by MaksymZerkakh** [comment]
Yeah It logged me in without a problem.
