### ISSUE TITLE
Podcast titles over the images

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/pgg-site#6]
in theloyaltyminute back end, can you please see what he titled for the recent past episodes are not being listed as an overlay on the attached images on the site.

Meaning, if you open a past episode to edit it, you should see the primary category and the "qt category" (for example episode 104 in the image attached, shows that in both the category and QT category insightful conversation is listed.)

So in this case on the front end of the website the title of this listing (episode title) should appear over those two images "The Loyalty Minute" and "Insightful Conversations" because they are (and should be) in both categories.

![Screenshot_20220410-084550_Chrome](https://user-images.githubusercontent.com/28393235/162629200-f917cb02-ed0c-4088-8c59-5f5249f7c308.jpg)
![Screenshot_20220410-084559_Chrome](https://user-images.githubusercontent.com/28393235/162629202-a5780039-bf5c-4bac-99d9-58c2164967dd.jpg)
![Screenshot_20220410-085811_Chrome](https://user-images.githubusercontent.com/28393235/162629204-44facd7a-6c14-456a-9610-d53fa2930467.jpg)

**Comment by MaksymZerkakh** [comment]
Ok, I added the Next Episode and Previous Episode buttons. I can change it to the titles of the Episodes but they are long and might be confusing for the users, let me know if this is ok or if you want the titles instead. This is on the staging environment at the moment https://theloyaltymstg.wpengine.com/episode-104-interview-with-peter-voss-ceo-at-aigo-ai/ .
